apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
spec:
  selector:
    matchLabels:
      app: backend-app
  replicas: {{ .Values.backendApp.replicaCount }}
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
        - name: backend
          image: {{ .Values.backendApp.image }}  # Correct reference
          
          ports:
            - containerPort: {{ .Values.backendApp.containerPort }}
         
